import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[url(https://res.cloudinary.com/dgccztjql/image/upload/v1697346840/products/cycorp/bg_final_zhnluy.jpg)] bg-cover`}>
        {/* <Navbar /> */}
        {children}</body>
    </html>
  )
}
